#/usr/bin/fish

alias c='clear'
alias ccc='curl ip-api.com'
alias cls='clear'
alias conda='/home/jithin/.local/conda/bin/conda'
alias ee='. .env'
alias gradle='./gradlew'
alias gt='gnome-terminal .'
alias jnb='jupyter notebook'
alias l='exa -l'
alias la='ls -Ah'
alias leet='cd ~/code/leetcode && vim vimconfig'
alias ll='exa -la'
alias ls='exa'
alias mm='cd /home/jithin/code/trainingtask/Windows'
alias nau='thunar'
alias pp='~/.local/venv/bin/python'
alias pw='readlink -f *'
alias ref='~/.local/share/auto/display-settings'
alias sedit='sudoedit'
alias serve='~/.local/venv/bin/python -m host'
alias so='source'
alias svim='sudoedit'
alias swap='xmodmap -e "clear lock" && xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock" && xmodmap -e "keycode 66 = Escape NoSymbol Escape"'
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
alias touchenv='echo ". .venv/bin/activate.fish" > .env'
alias webp2gif='magick mogrify -format gif *.webp && rm *.webp'
alias xx='xrandr --output eDP-1-1 --off'
alias yy='yay -Syu --noconfirm'
alias vimg='vim +G'
