#/usr/bin/fish

alias c='clear'
alias ccc='curl ip-api.com'
alias cls='clear'
alias ee='. .env'
alias l='exa -l'
alias la='ls -Ah'
alias leet='cd ~/code/leetcode && vim vimconfig'
alias ll='exa -la'
alias ls='exa'
alias nau='thunar'
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
alias touchenv='echo ". .venv/bin/activate.fish" > .env'
alias vimg='vim +G'
alias webp2gif='magick mogrify -format gif *.webp && rm *.webp'
alias yy='yay -Syu --noconfirm'
