"$schema" = 'https://starship.rs/config-schema.json'
format = "$directory$all"

add_newline = true

[character] 
success_symbol = "[->](green)" 
error_symbol = "[->](red)" 

[package]
disabled = true

[line_break]
disabled = true

[git_commit]
commit_hash_length = 4

[git_branch]
symbol = "🌱"
format = "[\\[$branch\\]](bold #A31F39) "

[git_status]
disabled=true

[cmd_duration]
disabled=true

[directory]
truncation_length = 3
